import "../styles/dashboard/dashboard-page.css";
import "../styles/layout/navbar.css";
import "../styles/layout/sidebar.css";
import "../styles/dashboard/dashboard-welcome.css";
import "../styles/dashboard/dashboard-stats.css";
import "../styles/dashboard/dashboard-quick-actions.css";
import "../styles/dashboard/dashboard-progress-chart.css";
import "../styles/dashboard/dashboard-recent-assignments.css";
import "../styles/dashboard/dashboard-templates-promo.css";

import "../styles/loading-screen/loading-screen.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
